Archana90663/New_PasteBin

Server/app.go, Server/postText.go
=> Add Title to text #31

Server/allTexts.go, Server/app.go
resolves #29 
route:-
```
GET /api/allTexts
```
Response Types
```
type Text struct {
id        string,
body      string,
title     string,
created_at datetime
}
```
```
type AllTextsResponse struct {
Texts []Text
}
```
Sample Response:-
```
{
"texts": [
{
"id": "cdcb85b5-43e3-40cf-a739-e3c3eb0b7b7e",
"body": "adsf",
"title": "",
"created_at": "2022-01-27T18:41:19.535736-05:00"
},
{
"id": "8c372e52-35f5-418e-bcb0-3227b9c3c1c1",
"body": "fff",
"title": "ww",
"created_at": "2022-01-27T20:14:44.335296-05:00"
}
]
}
```
=> Route to get the list of all texts #29

Server/allTexts.go, Server/app.go
resolves #34 
updated route:-
route:-
```
GET /api/allTexts
```
Response Types
```
type TextListing struct {
id        string,
title     string,
created_at datetime
}
```
```
type AllTextsResponse struct {
texts []TextListing
}
```
Sample Response:-
```
{
"texts": [
{
"id": "cdcb85b5-43e3-40cf-a739-e3c3eb0b7b7e",
"title": "aa",
"created_at": "2022-01-27T18:41:19.535736-05:00"
},
{
"id": "4d7162ab-f353-40ac-a67a-9d538ee5389b",
"title": "ww",
"created_at": "2022-01-27T20:32:33.171927-05:00"
}
]
}
```
=> Update route for All texts to only return id, title, date #34

Server/app.go, Server/getText.go
resolves #30 
Created a route to get a text by ID
route:-
```
POST /api/getText
```
request format JSON:-
```
{
"id": string,
}
````
sample request:-
```
{
"id": "cdcb85b5-43e3-40cf-a739-e3c3eb0b7b7e"
}
```
Response:
```
{
"id": string,
"body": string,
"title": string,
"created_at": datetime
}
```
Sample Response:
```
{
"id": "cdcb85b5-43e3-40cf-a739-e3c3eb0b7b7e",
"body": "adsf",
"title": "",
"created_at": "2022-01-27T18:41:19.535736-05:00"
}
```
Not Found Response:-
returns `404 Not Found`
```
{
"error": string
}
```
Bad request response:-
returns `400 Bad Request`
```
{
"error": string
}
```
Server error response:-
return `500 Internal Server Error`
=> Route text

Server/app.go
=> Typing url now working with angular router and embed+mux #47

Server/app.go, Server/postText.go
resolves #45
Updated Route Info
route:-
```
POST /api/submitText
```
request format JSON:-
```
{
"title": string,
"body": string
}
````
sample request:-
```
{
"title": "ttt",
"body": "adsf"
}
```
Success Response:-
returns `201 created`
```
{
"id": string
}
```
Sample Response:-
```
{
"id": "2039354c-4445-407e-9c03-742e23cecddf"
}
```
Bad request response:-
returns `400 Bad Request`
```
{
"error": string
}
```
Server error response:-
return `500 Internal Server Error`
=> Return Id in addText route #45

Server/app.go, Server/go.mod, Server/go.sum
=> Enable CORS #52

new_pastebin_frontend/src/app/app-routing.module.ts, new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/navbar/navbar.component.html, new_pastebin_frontend/src/app/testpage/persontype.ts, new_pastebin_frontend/src/app/testpage/testpage.component.html, new_pastebin_frontend/src/app/testpage/testpage.component.spec.ts, new_pastebin_frontend/src/app/testpage/testpage.component.ts
resolves #24 
test page is created to send request and display dummy data
=> Send request to test route from front-end to back-end. #24

new_pastebin_frontend/angular.json, new_pastebin_frontend/package-lock.json, new_pastebin_frontend/package.json, new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/index.html, new_pastebin_frontend/src/styles.css
Initialized Angular Material into the project, verified the setup does not break any other code or functionality.
Resolves #5
=> Initialized Angular Material

new_pastebin_frontend/package-lock.json, new_pastebin_frontend/package.json, new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.html, new_pastebin_frontend/src/index.html
Added Angular text editor library and some code to edit the size down the road.
Resolves #2
=> #2 Text editor lib implemented

Server/postText.go
resolves #10 
route:-
```
POST /api/submitText
```
request format JSON:-
```
{
"title": string,
"body": string,
"expire_at": datetime //Optional
}
````
sample requests:-
```
{
"title": "ttt",
"body": "adsf"
}
```
```
{
"title": "dd",
"body": "dd",
"expire_at": "2022-01-31T21:23:21.184827-05:00"
}
```
Success Response:-
returns `201 created`
```
{
"id": string
}
```
Sample Response:-
```
{
"id": "2039354c-4445-407e-9c03-742e23cecddf"
}
```
Bad request response:-
returns `400 Bad Request`
```
{
"error": string
}
```
Server error response:-
return `500 Internal Server Error`
route:-
```
POST /api/getText
```
request format JSON:-
```
{
"id": string,
}
````
sample request:-
```
{
"id": "cdcb85b5-43e3-40cf-a739-e3c3eb0b7b7e"
}
```
Response:
```
{
"id": string,
"body": string,
"title": string, …
```
=> Store expiration dates for texts #10

new_pastebin_frontend/src/app/submitpage/submitpage.component.html
Created a title box for submitting the text. Present in the submitpage.component.html file
Resolves #62
=> #62 Added title box for submitpage

new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/homepage/homepage.component.ts, new_pastebin_frontend/src/app/homepage/pastestype.ts
Obtain raw pastes information and display it on the home page.
=> #9 Displaying Paste Info and Titles

Server/app.go, Server/go.mod, Server/go.sum
=> Fix CORS for POST requests Fixes #74

new_pastebin_frontend/src/app/app.component.css, new_pastebin_frontend/src/app/app.component.html
=> Create a container for all content #78

Server/allTexts.go
update `TextListing` format for route `/api/allTexts`
```
type TextListing struct {
id        string,
title     string,
created_at datetime,
expire_at  datetime
}
```
=> Fix allTexts request fields #81

Server/app.go
=> Fix error message with empty title #86

new_pastebin_frontend/src/app/homepage/homepage.component.html
=> Open specific text page #89

new_pastebin_frontend/src/app/textpage/textpage.component.ts
=> #92 Show 404 on view text page with wrong id in link

Server/postText.go
=> Fix time zone while storing in db #95

new_pastebin_frontend/src/app/pagenotfound/pagenotfound.component.css, new_pastebin_frontend/src/app/pagenotfound/pagenotfound.component.html
=> center align the error message 404 #98

new_pastebin_frontend/src/app/homepage/homepage.component.css
=> Create hover animation on homepage cards #99

Server/postText.go
=> Embed IP location db file #77

Server/removeExpired.go
=> #104 Metadata deleted when post is expired

new_pastebin_frontend/src/app/submitpage/submitpage.component.html, new_pastebin_frontend/src/styles.css
Added some Angular Material styling to all the remaining components in the submit page. Inputs are also working for all (title, body, expiration date).
Resolves #101
=> #101 Added Angular Material to the submit-page components

new_pastebin_frontend/src/app/submitpage/submitpage.component.html, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts
P tags were being shown initially when submitting text, but now added a filter to remove the tags when data is being sent and displayed. 
Resolves #107
=> #107 Fixed p tags being shown in a new post

new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/navbar/navbar.component.html, new_pastebin_frontend/src/app/submitpage/submitpage.component.html, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts
=> Upgrade the look of submit text page #111

new_pastebin_frontend/src/app/app.component.css, new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/submitpage/submitpage.component.html
=> Increase margins across all pages #117

Sprint1.md
Created a new file called Sprint1.md which specifies what we accomplished in Sprint 1.
Resolves #113
=> #113 created file Sprint1.md

new_pastebin_frontend/package-lock.json, new_pastebin_frontend/package.json, new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/homepage/homepage.component.ts
Added a search bar functionality to search for posts via their titles.
Resolves #124
=> #124 Created a search bar

new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/submitpage/submitpage.component.html, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts, new_pastebin_frontend/src/app/types/pastestype.ts
Added post tag types such as Public, Private, and Unlisted to the Paste class and interfaces. Also added them in the backend. 
Resolves #121 and #122
=> #121 Added tag types to the Paste type

new_pastebin_frontend/angular.json
=> Change initial budget in angular #137

makefile
=> Update build in makefile to accommodate assets #139

Server/allTexts.go
=> Only return public pastes #143

new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/homepage/homepage.component.ts
Added a drop-down list for the user to pick how they want to view their posts: Newest, Oldest, Alphabetically.
Resolves #125
=> #125 Added filters to view posts as such

Server/getText.go
=> Don't return user ip when fetching paste #149

.gitignore, Server/getText_test.go
=> Golang unit test for getText #151

Server/allTexts.go
=> return allTexts in descending order #156

makefile
=> make target for test #153

Server/postText_test.go
=> unit test for postText #155

Server/allTexts_test.go
=> unit test for allTexts #154

.gitignore, makefile
=> run cypress tests on test make target #165

Server/removeExpired.go, Server/removeExpired_test.go
=> Test expire post #163

pastebin_tests.postman_collection.json
resolves #167 
To run the postman tests, run the following command in the project directory while the project is running.
```
npx newman run pastebin_tests.postman_collection.json
```
=> Postman test for submitText #167

pastebin_tests.postman_collection.json
resolves #168 
To run the postman tests, run the following command in the project directory while the project is running.
```
npx newman run pastebin_tests.postman_collection.json
```
=> Postman test for submitText with tag #168

pastebin_tests.postman_collection.json
resolves #169 
To run the postman tests, run the following command in the project directory while the project is running.
```
npx newman run pastebin_tests.postman_collection.json
```
=> Postman test for submitText with empty body #169

pastebin_tests.postman_collection.json
resolves #170 
To run the postman tests, run the following command in the project directory while the project is running.
```
npx newman run pastebin_tests.postman_collection.json
```
This test case will fail until #166 is done.
=> Postman test for submitText with an invalid tag #170

new_pastebin_frontend/src/app/loginpage/loginpage.component.html, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.html, new_pastebin_frontend/src/app/navbar/navbar.component.ts, new_pastebin_frontend/src/app/testpage/testpage.component.html
Implemented remaining parts of the login functionality such as verifying if user is logged in and changing the "Login" button to "Logout" in the navbar.
Resolves #128
=> #128 Finished remaining changes to login functionality

Server/get_db_release.go, Server/get_db_testing.go
=> Fix build tags #186

Server/app.go
=> Validates tags on posts, solves issue #166

new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/homepage/homepage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.ts
If the user is logged in, the homepage is personalized to say "Welcome [username]!" and if they're logged out, it only shows "Welcome!"
Resolves #188
=> #188 Added user's name to the welcome page

new_pastebin_frontend/src/app/homepage/homepage.component.spec.ts, new_pastebin_frontend/src/app/homepage/homepage.component.ts
Pair programmed with @bkojusner to determine if the correct paste filter is being chosen by the user. The expected output (which is a string) is compared manually to what we expect the correct answer is.
Resolves #193
=> #193 passing test cases to check if paste filter clicked is correct

new_pastebin_frontend/src/app/submitpage/submitpage.component.spec.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts
Pair programmed with @bkojusner to create unit test for determining if the paste tag is "Public" so that only those pastes will be displayed on the homepage. 
Resolves #192
=> #192 passing test cases for checking the appropriate paste tag

new_pastebin_frontend/cypress/integration/security_spec.js, new_pastebin_frontend/src/app/homepage/homepage.component.html
Security Testing Added for four types of vulnerabilities
Resolved #130
=> Bkojusner security tests

Server/postText_test.go
Existence of Created At time of a post is tested.
=> Test for existence of Created At time of the post, issue #162

new_pastebin_frontend/src/app/loginpage/loginpage.component.html
Added Angular material to User Information and Logout option displayed on site.
Resolves #190
=> Bkojusner logout material

new_pastebin_frontend/cypress/integration/social_login_spec.js, new_pastebin_frontend/src/app/loginpage/loginpage.component.html
Created tests for the Social Login and Logout functionality
Resolves #131
=> Bkojusner login tests

Server/app.go
resolves #211
A route to get user info
route:-
```
GET /api/login
```
Request Cookies
The cookie `pb-login-token` must be set. This can be done by the route `/api/login`.
Response:
```
{
"id": string,
"email": string,
"handle": string
}
```
Sample Responses:
```
{
"id": "101279230808345737938",
"email": "test@tt.t",
"handle": "aa"
}
```
Not logged in response:-
returns `401 Unauthorized`
Server error response:-
return `500 Internal Server Error`
=> user info route #211

Server/app.go
resolves #209 
Route to logout.
route:-
```
GET localhost:8080/api/logout
```
Success Response:-
returns `200 OK`
Deletes the cookie named `pb-login-token`
No session found response:-
returns `404 Not Found`
```
{
"error": string
}
```
=> logout route #209

new_pastebin_frontend/src/app/loginpage/loginpage.component.html
Since we have an "Account Profile" page set up for the user to see their information, we don't have to display it again in the "Logout" page, thus I've removed them.
Resolves #205
=> #205 removed user information from the logout page

new_pastebin_frontend/src/app/profilepage/profilepage.component.html, new_pastebin_frontend/src/styles.css
Styling the "Account Profile" page step by step so that it looks nicer. Adding commits to each of the step to view it accordingly and suggest any changes. 
Resolves #204
=> #204 Adding styling to the user profile

new_pastebin_frontend/src/app/loginpage/loginpage.component.spec.ts, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.spec.ts
Added a unit test in Angular to detect if the logged-in user's information is correctly being stored and extracted by the application. Passing 2/2 tests. 
Resolves #226
=> #226 Added unit test to assess if user info is correctly extracted

Server/app.go
=> cookies work with cors #256

new_pastebin_frontend/src/app/app-routing.module.ts, new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/navbar/navbar.component.html, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts, new_pastebin_frontend/src/app/types/pastestype.ts, new_pastebin_frontend/src/app/viewpage/viewpage.component.html, new_pastebin_frontend/src/app/viewpage/viewpage.component.spec.ts, new_pastebin_frontend/src/app/viewpage/viewpage.component.ts
Create a page called "viewpage" in which the logged in user can see the pastes they've created. Checks to make sure it's the correct user and if they're logged in.
=> #202 Displays the pastes created by the user when logged in

new_pastebin_frontend/src/app/app-routing.module.ts, new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/navbar/navbar.component.html, new_pastebin_frontend/src/app/viewpage/viewpage.component.html, new_pastebin_frontend/src/app/viewpage/viewpage.component.spec.ts, new_pastebin_frontend/src/app/viewpage/viewpage.component.ts
Currently working on steps to display those pastes that the logged-in user has created. 
Resolves #202
=> #202 Added viewpage to the navbar for easy access

new_pastebin_frontend/src/app/submitpage/submitpage.component.ts, new_pastebin_frontend/src/app/types/pastestype.ts, new_pastebin_frontend/src/app/viewpage/viewpage.component.html, new_pastebin_frontend/src/app/viewpage/viewpage.component.ts
Made some git mistakes, created new branch that has both Steps 1 and 2 completed. Added "viewpage" page for the user to view their pastes. Added to the navbar and displayed all the pastes.
=> #202 Displays user's pastes, the ones they created, when logged in

new_pastebin_frontend/src/app/loginpage/loginpage.component.spec.ts, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.ts
Added a test case in Angular unit testing to determine if our login functionality is working. Passing the test case! 
Resolves #227
=> #227 Added unit test to assess if login functionality is working

new_pastebin_frontend/src/app/loginpage/loginpage.component.spec.ts, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts
Added a unit test in Angular to determine if the Google Login API for logging out works in our application. Passing the test case!
Resolves #248
=> #248 Added unit test to determine if logout functionality works

new_pastebin_frontend/src/app/submitpage/submitpage.component.spec.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts
Will be adding two types of unit tests to check that an anonymous user can only choose "public" or "Unlisted" and cannot pick "Private" unless logged in. Passing test cases!
Resolves #252
=> #252 Created unit test to check only public/unlisted tag can be checked

new_pastebin_frontend/src/app/aboutpage/aboutpage.component.css, new_pastebin_frontend/src/app/aboutpage/aboutpage.component.html, new_pastebin_frontend/src/app/aboutpage/aboutpage.component.spec.ts, new_pastebin_frontend/src/app/aboutpage/aboutpage.component.ts, new_pastebin_frontend/src/app/app-routing.module.ts, new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/navbar/navbar.component.html
Took care of the four tasks mentioned in issue #222. Added a mention on the first Pastebin, explained what we improve upon in our Pastebin, explain how it is done, and briefly mention the team.
Resolves #222
=> Bkojusner aboutpage

new_pastebin_frontend/src/app/loginpage/loginpage.component.ts
Logout route added to frontend
=> #272 Logout route added

new_pastebin_frontend/src/app/loginpage/loginpage.component.html, new_pastebin_frontend/src/app/loginpage/loginpage.component.spec.ts, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.spec.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts, new_pastebin_frontend/src/app/textpage/textpage.component.ts
Added unit test to check that a logged in user can select the "Private" tag option when creating a paste. Passing test case! 
Did not add a test to check if user is logged in for this issue as it was already added when testing if the user is logged in, in a previous issue.
Resolves #247
=> #247 Added unit test to check only logged in user can select private tag

new_pastebin_frontend/src/app/loginpage/loginpage.component.html, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts, new_pastebin_frontend/src/app/textpage/textpage.component.ts
There was some old code that was wrong on the main branch. Created new branch to remove all the old code and revert it back to the original.
Resolves #277
=> #277 Removed old wrong code and reverted back

new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts, new_pastebin_frontend/src/app/textpage/textpage.component.ts
Updated the navbar so that the error is removed. Now, it should show the tabs according to whether the user is logged in or not.
Resolves #279
=> #279 Updated navbar so that it correctly shows tabs for logged in users

new_pastebin_frontend/src/app/app.component.ts, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts, new_pastebin_frontend/src/app/textpage/textpage.component.ts
Used a hashmap to store all the pastes. It is now correctly displaying the userID's of the users who created those pastes. May not be the most efficient, we can debug this further in the next sprint.
Resolves #281
=> #281 paste userID's show the correct ID's of their creators

new_pastebin_frontend/cypress/integration/non-loggedin_paste.js
Created Cypress test that checks if a user is not logged in and verifies that they can not make private pastes.
Resolves #266
=> Bkojusner test publicandunlistedonly

new_pastebin_frontend/src/app/viewpage/viewpage.component.css, new_pastebin_frontend/src/app/viewpage/viewpage.component.html
Fixed and Styled the View Pastes page for the user. It now displays their username and full name to them along with their profile picture and an aesthetically pleasing change of color in their pastes so they can visually recognize that those pastes were originally created by them.
Resolves #253
=> Bkojusner view pastes aesthetic

new_pastebin_frontend/cypress/integration/loggedin_tag_update.js
This test checks if a user is logged in and then sees the different paste permissions they have available to them.
Resolves #265
=> Bkojusner test loggedintagupdate

new_pastebin_frontend/cypress/integration/logging_out_spec.js
Cypress code that tests to see if an already logged in user can successfully logout from the site.
Resolved #268
=> Bkojusner test loggingout

new_pastebin_frontend/src/app/loginpage/loginpage.component.html, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.html, new_pastebin_frontend/src/app/navbar/navbar.component.ts
Login button in the navbar directly leads to the Google API login. Thanks to @Archana90663 for the provided alternative solution to my original attempt.
Resolves #206
=> Bkojusner navbar login

new_pastebin_frontend/src/app/navbar/navbar.component.html, new_pastebin_frontend/src/app/navbar/navbar.component.ts
Logout button does not redirect to a logout page, rather it automatically logs out the user and sends them to the home page.
Resolves #207
=> #207 Finished Logout Redirect

new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/homepage/homepage.component.ts
Changed homepage to display the appropriate user information for posts that were created by a user that is logged in.
Resolves #220
=> Bkojusner pastecard display

new_pastebin_frontend/src/app/homepage/homepage.component.html
Initially, the profile pic of the user who created the most recent paste was showing for all the pastes in the homepage. Now, the user's profile pic only shows for the paste they created.
Resolves #302
=> #302 pastes not show profile pic according to the user who created them

new_pastebin_frontend/src/app/textpage/textpage.component.html
When a user clicks on the paste to view it, they can now see the user's profile picture and username. If an un-logged in user is the one who created it, then it's the default pic and username.
Resolves #304
=> #304 viewing a paste now shows the user's profile pic and username

new_pastebin_frontend/cypress/integration/userID_paste_match.js
Cypress test that creates a paste and then goes to the front page to check if the paste exists and if it is credited as being created by the test subject.
Resolves #267
=> #267 Creates paste and checks the combined userID and pasteID exist

new_pastebin_frontend/cypress/integration/data_integrity_spec.js, new_pastebin_frontend/cypress/integration/userID_paste_match.js
Cypress test that creates a paste and checks whether or not it exists in the home page in order to maintain data integrity on the paste.
Resolves #219
=> Bkojusner test dataintegrity

new_pastebin_frontend/src/app/navbar/navbar.component.ts
When user logs in or logs out, the navbar now updates accordingly.
Resolves #309
=> #309 navbar now updates according to user is logged in or not

new_pastebin_frontend/src/app/homepage/homepage.component.ts, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.ts
Fixed the issue that user keeps logging out after refreshing the page. The session now remembers the user even after they refresh the page. The only way out is for the user to log out.
Resolves #263
=> #263 User now remains logged in after refreshing page

new_pastebin_frontend/src/app/homepage/homepage.component.ts, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.ts
User no longer has to manually refresh the page to see the changes. Added automatic refreshing so that once the user logs in, they can see the new changes.
Resolves #318
=> #318 Automatic refresh shows the new logged in changes

new_pastebin_frontend/src/app/loginpage/loginpage.component.ts, new_pastebin_frontend/src/app/navbar/navbar.component.ts, new_pastebin_frontend/src/app/profilepage/profilepage.component.ts
The "Account Profile" page now shows the user details correctly according to the user who's logged in.
Resolves #319
=> #319 Account Profile now showing user details

new_pastebin_frontend/src/app/submitpage/submitpage.component.ts, new_pastebin_frontend/src/app/textpage/textpage.component.ts
The issue was that the logged in user was not being access correctly. Fixed this by calling localStorage and now a logged in user can get all 3 paste tag options. An anonymous user can only get the 2 paste tag options.
Resolves #324
=> #324 Logged in user now gets all paste options

new_pastebin_frontend/src/app/loginpage/loginpage.component.ts
=> remove signup request from frontend #335

makefile
=> postman tests from makfile #340

new_pastebin_frontend/src/app/homepage/homepage.component.spec.ts, new_pastebin_frontend/src/app/homepage/homepage.component.ts
Created a unit test, in Angular, that checks to see if the user is still valid in the localStorage after refreshing. Passing 1/1 tests! 
Resolves #317
=> #317 Created unit test to check user logged in after refresh

new_pastebin_frontend/src/app/profilepage/profilepage.component.spec.ts, new_pastebin_frontend/src/app/profilepage/profilepage.component.ts
Created a unit test to check if the user information (such as name, email, photoImg) are not null in the Account Profile page. Passing 1/1 test! 
Resolves #321
=> #321 Created unit test to check user information is not null

README.md
Added a 200 word application description as per the assignment.
=> Update readme with application description

new_pastebin_frontend/src/app/submitpage/submitpage.component.spec.ts, new_pastebin_frontend/src/app/submitpage/submitpage.component.ts
Added some more unit tests to check if all other functionalities are working correctly in this component. Passing all test cases!
Resolves #348
=> #348 created more unit tests for submitpage component

new_pastebin_frontend/src/app/homepage/homepage.component.spec.ts, new_pastebin_frontend/src/app/homepage/homepage.component.ts
Created more unit tests to check if functionalities are working properly in the homepage. Passing test cases! 
Resolves #349
=> #349 Added more unit tests for homepage component

new_pastebin_frontend/src/app/viewpage/viewpage.component.spec.ts, new_pastebin_frontend/src/app/viewpage/viewpage.component.ts
Added unit tests to see if all functionalities are working properly. Passing test cases!
Resolves #350
=> #350 created unit tests to check if viewpage works properly

new_pastebin_frontend/src/app/app-routing.module.ts, new_pastebin_frontend/src/app/app.module.ts, new_pastebin_frontend/src/app/navbar/navbar.component.html, new_pastebin_frontend/src/app/signuppage/signuppage.component.css, new_pastebin_frontend/src/app/signuppage/signuppage.component.html, new_pastebin_frontend/src/app/signuppage/signuppage.component.spec.ts, new_pastebin_frontend/src/app/signuppage/signuppage.component.ts
Pushing through additions to the sign-up page. We have discussed the different routes we can take issues relating to sign-up and at the moment it is best to record this progress and focus on other tasks.
Progress towards #311
=> Bkojusner signup page

new_pastebin_frontend/src/app/profilepage/profilepage.component.spec.ts, new_pastebin_frontend/src/app/profilepage/profilepage.component.ts
Created some more unit tests to make sure functionalities are working correctly in the profilepage component.
Resolves #351
=> #351 Added unit tests to check on profilepage component

new_pastebin_frontend/src/app/loginpage/loginpage.component.spec.ts, new_pastebin_frontend/src/app/loginpage/loginpage.component.ts
Created more unit tests to assess that the functionalities for this component are working correctly. Passing test cases!
Resolves #352
=> #352 added unit tests for loginpage

makefile
=> server not closed after test #371

cypress/integration/pastes_test_spec.js, new_pastebin_frontend/cypress/integration/data_integrity_spec.js, new_pastebin_frontend/cypress/integration/security_spec.js, new_pastebin_frontend/cypress/integration/userID_paste_match.js
=> change editor in cypress tests #378

makefile
=> makefile target for closing server #380

makefile
=> Close server on error in make #387

Server/app.go
=> validate language in backend #390

Server/allTexts.go
=> return author details in allTexts route #400

new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/homepage/homepage.component.ts
=> remove map from homepage component #404

new_pastebin_frontend/cypress/integration/homepage_spec.js
Wrote five Cypress tests to verify the Homepage component works. The first test checks for a null value in the body of a paste. The second test verifies a user is not considered logged in and the third test checks that this user can not create a private paste. The fourth test checks an already created paste to ensure that the user should be anonymous and the fifth test searches for a paste to ensure the search functionality works.
Resolves #356
=> Bkojusner homepage cypress

new_pastebin_frontend/cypress/integration/textpage_spec.js
Creates a new paste and verifies that the information on there is exactly what was put in by the user. Then goes on to visit the text page for the paste and verifies the username, userID, date, title, and body of the paste. All tests pass.
Resolves #360
=> Bkojusner textpage cypress

new_pastebin_frontend/src/app/homepage/homepage.component.html, new_pastebin_frontend/src/app/profilepage/profilepage.component.html, new_pastebin_frontend/src/app/textpage/textpage.component.html
=> User image not showing #413

makefile
=> update makefile testing #419

new_pastebin_frontend/src/app/viewpage/viewpage.component.ts
=> Remove map from view page #415

new_pastebin_frontend/src/app/viewpage/viewpage.component.html, new_pastebin_frontend/src/app/viewpage/viewpage.component.ts
=> In viewpage display user info from db #424
